clean:
  mod_options:
  categories:
    - lift
    - olympic lift
push-up:
  mod_options:
    - decline
    - hand release
    - knee
    - clapping
  categories:
    - body-weight
air squat:
  mod_options:
    - jumping
  categories:
    - body-weight
thruster:
  mod_options:
  categories:
    - lift
pull-up:
  mod_options:
    - strict
    - kipping
    - chest-to-bar
    - weighted
    - band
  categories:
    - body-weight
    - lift
