types:
  Farmer's Carry
  Air Squat
  Back Extension
  Ball Slams
  Bar Muscle-up
  Box Jump
  Burpees
  Clean and Jerk
  Dip
  Double Unders
  Dumbell Snatch
  Dumbell Split Lifts
  Kipping Pull-up
  Front Squat
  Glute-Ham Sit-up
  Handstand Push-up
  Handstand
  Hang Clean
  Hang Power Clean
  Hang Power Snatch
  Hang Snatch
  Heaving Snatch Balance
  Hip Extension
  Hip-back Extension
  Jerk
  Jerk (behind the head)
  Rope Climb
  Jumping Squats
  Jumping Pullups
  Kettlebell Snatch
  Kettlebell Swings
  Knees to Elbows
  L-sit
  Medicine Ball Cleans
  Muscle-up
  Overhead Squatting Safely
  Overhead Squat
  Power Clean
  Power Snatch
  Pressing Snatch Balance
  Push Jerk
  Push Press
  Push-up
  Ring Dips
  Shoulder Press
  Snatch
  Snatch Balance
  Thruster
  Wall Ball
  Walking Lunges
